#!/usr/bin/env python3
"""
Example script to read Sonar 3D-15 data from a file and decode the packets.
The sonar file can be generated with the "save_sonar_data.py" script or in the Sonar GUI (release 1.4.0 or later).

Optionally it can save the RangeImage data to XYZ file format and BitmapImage
to PGM file format.

REQUIREMENTS:
  - Python 3
  - protobuf (pip install protobuf)
  - sonar_3d_15_protocol_pb2.py generated from the Water Linked sonar .proto file

USAGE:
  1. Place this script in the same folder as the "sonar_3d_15_protocol_pb2.py" file (generated by protoc).
  2. Run: python save_sonar_data.py --file <filename> [--save]
  3. Observe the output in the terminal.
"""

import os
import struct
import zlib
import math

import numpy as np
from enum import Enum


import rospy
from std_msgs.msg import UInt8MultiArray
from sensor_msgs.msg import Image
from sensor_msgs.msg import PointCloud
from geometry_msgs.msg import Point32
from sensor_msgs.msg import ChannelFloat32

from cv_bridge import CvBridge, CvBridgeError

SONAR3D_FRAME = "sonar3d"
SONAR_RAW_DATA_TOPIC = f'{SONAR3D_FRAME}/raw_data_multibyte'
SONAR_RANGE_IMAGE_TOPIC = f'{SONAR3D_FRAME}/range_image'
SONAR_POINT_CLOUD_TOPIC = f'{SONAR3D_FRAME}/point_cloud'
YEAR_CHECK = 2023 # year check as there are some messages that have year 0 or 1
TIME_FORMAT =  "%Y-%m-%d-%H-%M-%S"
RAW_DATA_FILE_PREFIX = "sonar-capture-"
USE_SENSOR_STAMP = False # use sensor timestamp (True) or current time (False)


class Modes(Enum):
    FILE = 1
    ROS = 2
    ADD_BAG = 3

pub_range_image = None
pub_point_cloud = None
bridge = None
use_sensor_stamp = USE_SENSOR_STAMP #

# Generated Protobuf definitions for the Sonar 3D-15 protocol
from sonar_3d_15_protocol_pb2 import (
    Packet,
    BitmapImageGreyscale8,
    RangeImage
)

def parse_rip1_packet(data: bytes):
    """
    Parse the RIP1 framing:
      1. Verify the "RIP1" magic header
      2. Verify total_length field matches the data size
      3. Check CRC
      4. Extract payload (proto data) from the packet

    Returns:
      payload (bytes) if valid, or None if there's an error.
    """
    if len(data) < 13:
        print(f"Packet too small: only {len(data)} bytes.")
        return None

    # First 4 bytes are "RIP1"
    magic = data[:4]
    if magic != b'RIP1':
        print(f"Invalid magic: got {magic!r} instead of b'RIP1'.")
        return None

    # Next 4 bytes (little-endian) specify the total packet length
    total_length = struct.unpack('<I', data[4:8])[0]
    if len(data) < total_length:
        print(
            f"Packet truncated: needed {total_length} bytes, got {len(data)}.")
        return None

    # The payload is between offset 8 and (total_length - 4)
    payload = data[8: total_length - 4]

    # Last 4 bytes in the packet is the CRC32
    crc_received = struct.unpack('<I', data[total_length - 4: total_length])[0]
    crc_calculated = zlib.crc32(data[: total_length - 4]) & 0xffffffff
    if crc_calculated != crc_received:
        print(
            f"CRC mismatch: expected 0x{crc_calculated:08x}, got 0x{crc_received:08x}.")
        return None

    return payload


def decode_protobuf_packet(payload: bytes):
    """
    Decode the Protobuf Packet (top-level), which may contain:
      - BitmapImageGreyscale8
      - RangeImage
      - or an unknown message type (google.protobuf.Any)

    Returns:
      (msg_type_name, message_object) if successfully parsed,
      or None if parsing failed.
    """
    # Create a top-level Packet object
    packet = Packet()
    try:
        packet.ParseFromString(payload)
    except Exception as e:
        print(f"Protobuf parse error: {e}")
        return None

    # The actual data is in the .msg field (type google.protobuf.Any)
    any_msg = packet.msg
    if not any_msg.IsInitialized():
        return None

    # Attempt to unpack into BitmapImageGreyscale8
    bmp = BitmapImageGreyscale8()
    if any_msg.Unpack(bmp):
        return ("BitmapImageGreyscale8", bmp)

    # Otherwise, try to unpack into RangeImage
    rng = RangeImage()
    if any_msg.Unpack(rng):
        return ("RangeImage", rng)

    # If it's neither of the above, return Unknown
    return ("Unknown", any_msg)


def rangeImageToXYZ(ri, msg=None):
    """
    Convert RangeImage data to a list of voxels with X, Y, Z coordinates.
    """
    max_pixel_x = ri.width - 1
    max_pixel_y = ri.height - 1
    fov_h = math.radians(ri.fov_horizontal)
    fov_v = math.radians(ri.fov_vertical)

    if msg is not None:
        msg.channels.append(ChannelFloat32(name="yaw"))
        msg.channels.append(ChannelFloat32(name="pitch"))
        msg.channels.append(ChannelFloat32(name="distance"))
    else:
        voxels = []

    for pixel_x in range(ri.width):
        for pixel_y in range(ri.height):
            pixel_value = ri.image_pixel_data[pixel_y * ri.width + pixel_x]
            if pixel_value == 0:
                # No data for this pixel
                continue

            yaw_rad = (pixel_x / max_pixel_x) * fov_h - fov_h / 2
            pitch_rad = (pixel_y / max_pixel_y) * fov_v - fov_v / 2
            distance_meters = pixel_value * ri.image_pixel_scale

            x = distance_meters * math.cos(pitch_rad) * math.cos(yaw_rad)
            y = distance_meters * math.cos(pitch_rad) * math.sin(yaw_rad)
            z = -distance_meters * math.sin(pitch_rad)

            if msg is not None:
                msg.points.append(Point32(x=x,y=y,z=z))
                msg.channels[0].values.append(yaw_rad)
                msg.channels[1].values.append(pitch_rad)
                msg.channels[2].values.append(distance_meters)
            else:
                voxel = {
                    "yaw": yaw_rad,  # yaw in radians
                    "pitch": pitch_rad, # pitch in radians
                    "distance": distance_meters, # distance in meters
                    "x": x, # x coordinate in meters
                    "y": y, # y coordinate in meters
                    "z": z # z coordinate in meters
                }

                voxels.append(voxel)

    if msg is None:
        return voxels


def saveXYZ(voxels, file_path):
    """
    Save the list of voxels to a file in XYZ format.
    Each voxel is represented as a line with x, y, z coordinates.
    """
    with open(file_path, 'w') as f:
        for voxel in voxels:
            x = voxel['x']
            y = voxel['y']
            z = voxel['z']
            f.write(f"{x} {y} {z}\n")
    print(f"Saved {len(voxels)} voxels to {file_path}")

def publishImage(bmpImg):
    """
    Save the BitmapImageGreyscale8 data to a file.
    The data is saved as a grayscale image in PGM format.
    """

    image = np.zeros((bmpImg.height, bmpImg.width, 1), dtype=np.uint8)

    # Write pixel data
    for y in range(bmpImg.height-1, 0, -1): # Flip the image vertically
        for x in range(bmpImg.width):
            image[y][x] = bmpImg.image_pixel_data[y * bmpImg.width + x]

    return image

def saveImage(bmpImg, file_path: str):
    """
    Save the BitmapImageGreyscale8 data to a file.
    The data is saved as a grayscale image in PGM format.
    """
    with open(file_path, 'wb') as f:
        f.write(b'P2\n') # PGM format identifier
        f.write(f"{bmpImg.width} {bmpImg.height}\n".encode()) # Write the width and height
        f.write(b'255\n')  # Max pixel value for PGM
        # Write pixel data
        for y in range(bmpImg.height-1, 0, -1): # Flip the image vertically
            for x in range(bmpImg.width):
                pixel_value = bmpImg.image_pixel_data[y * bmpImg.width + x]
                f.write(f"{pixel_value} ".encode())
            f.write(b'\n')
    print(f"Saved BitmapImage to {file_path}")

def handle_packet(data: bytes, mode: Modes = Modes.ROS, save_path: str = ""):
    # Parse the RIP1 framing to get the Protobuf payload
    payload = parse_rip1_packet(data)
    if payload is None:
        return  # skip invalid packets

    # Decode the Protobuf message
    result = decode_protobuf_packet(payload)
    if not result:
        # Did not get a valid message
        return

    msg_type, msg_obj = result
    #print(f"Received '{msg_type}' from {addr}")

    if msg_type == "BitmapImageGreyscale8":

        # Print out main fields
        print("  BitmapImageGreyscale8 data:")
        print(f"    Type: {msg_obj.type}")
        print(f"    Width x Height:  {msg_obj.width} x {msg_obj.height}")
        print(f"    Horizontal FoV:  {msg_obj.fov_horizontal}")
        print(f"    Vertical FoV:    {msg_obj.fov_vertical}")

        # Header info
        seq_id = msg_obj.header.sequence_id
        dt = msg_obj.header.timestamp.ToDatetime()
        print(f"    Sequence ID:     {seq_id}")
        print(f"    Timestamp (UTC): {dt.isoformat()}")
        if dt.year < YEAR_CHECK:
            return
        image = publishImage(msg_obj)

        try:
            # Convert the OpenCV image to a ROS Image message
            ros_image_msg = bridge.cv2_to_imgmsg(image, "mono8")
        except CvBridgeError as e:
            rospy.logerr(e)
            return
        
        ros_image_msg.header.seq = seq_id
        if use_sensor_stamp:
            ros_image_msg.header.stamp = rospy.Time.from_sec(dt.timestamp())
        else:
            ros_image_msg.header.stamp = rospy.Time.now()
        ros_image_msg.header.frame_id = SONAR3D_FRAME

        # Data
        if mode == Modes.FILE:
            filename = f"sonar_image_{seq_id}.pgm"
            file_path = os.path.join(save_path, filename)
            saveImage(msg_obj, file_path)
        elif mode == Modes.ROS:
            pub_range_image.publish(ros_image_msg)
        elif mode == Modes.ADD_BAG:
            return ros_image_msg

    elif msg_type == "RangeImage":
        # Print out main fields
        print("  RangeImage data:")
        print(f"    Width x Height:    {msg_obj.width} x {msg_obj.height}")
        print(f"    Horizontal FoV:    {msg_obj.fov_horizontal}")
        print(f"    Vertical FoV:      {msg_obj.fov_vertical}")
        print(f"    image_pixel_scale: {msg_obj.image_pixel_scale}")

        # Header info
        seq_id = msg_obj.header.sequence_id
        dt = msg_obj.header.timestamp.ToDatetime()
        print(f"    Sequence ID:         {seq_id}")
        print(f"    Timestamp (UTC):     {dt.isoformat()}")
        if dt.year < YEAR_CHECK:
            return

        # Convert to XYZ coordinates
        msg_point_cloud = PointCloud()
        msg_point_cloud.header.seq = seq_id
        if use_sensor_stamp:
            msg_point_cloud.header.stamp = rospy.Time.from_sec(dt.timestamp())
        else:
            msg_point_cloud.header.stamp = rospy.Time.now()
        msg_point_cloud.header.frame_id = SONAR3D_FRAME
        voxels = rangeImageToXYZ(msg_obj, msg_point_cloud)

        if voxels is not None:
            print(f"    Voxel count:         {len(voxels)}")
            if mode == Modes.FILE:
                # Save to XYZ file
                filename = f"sonar_voxels_{seq_id}.xyz"
                file_path = os.path.join(save_path, filename)
                saveXYZ(voxels, file_path)
        elif mode == Modes.ROS:
            pub_point_cloud.publish(msg_point_cloud)
        elif mode == Modes.ADD_BAG:
            return msg_point_cloud

    else:
        # We don't have a custom handler for other message types
        print(
            "  Received an unknown message type (not RangeImage or BitmapImage).")

    print()  # Extra blank line for readability


def sonar_msg_callback(msg):
    """
    Listen for Sonar 3D-15 UDP multicast packets on a specific port.
    - Filters packets based on the known Sonar IP address.
    - Parses the RIP1 framing.
    - Decodes the Protobuf message.
    - Prints relevant info (e.g. dimension, FoV, timestamp).
    """
    content = bytes(msg.data)

    packets = content.split(b'RIP1')
    for pkt in packets:

        # Parse the RIP1 framing to get the Protobuf payload
        handle_packet(b'RIP1' + pkt)

def parse_file(filename, mode: Modes = Modes.ROS, rosbag_file: str = None):
    """
    Listen for Sonar 3D-15 UDP multicast packets on a specific port.
    - Filters packets based on the known Sonar IP address.
    - Parses the RIP1 framing.
    - Decodes the Protobuf message.
    - Prints relevant info (e.g. dimension, FoV, timestamp).
    """
    # Set up a UDP socket with multicast membership

    with open(filename, 'rb') as f:
        content = f.read()

    from datetime import datetime, timezone

    # Define the timestamp string
    timestamp_str = filename.split(RAW_DATA_FILE_PREFIX)[1].rsplit('-', 1)[0]

    # Parse the string into a datetime object
    dt = datetime.strptime(timestamp_str, TIME_FORMAT)
    dt = dt.replace(tzinfo=timezone.utc)

    # Convert the datetime object to epoch time
    current_sonar_frame_time = dt.timestamp()
    previous_time = None

    # If we are saving data, create a directory for the files
    # Get the basename of the file without the extension
    # and use it as the directory name
    save_path = os.path.splitext(os.path.basename(filename))[0]
    if mode == Modes.FILE:
        os.makedirs(save_path, exist_ok=True)
    elif mode == Modes.ADD_BAG:
        import rosbag
        from std_msgs.msg import UInt8MultiArray

        output_bag_filename = '.'.join([w if i > 0 else f"{w}_w_sonar" for i, w in enumerate(rosbag_file.split('.'))])
        print(f"saving {rosbag_file} {output_bag_filename}")
        input_bag = rosbag.Bag(rosbag_file, 'r')
        input_bag_iterator = input_bag.read_messages()
        output_bag = rosbag.Bag(output_bag_filename, 'w') 

    non_valid_packets = 0
    packets = content.split(b'RIP1')
    for pkt in packets:
        # Parse the RIP1 framing to get the Protobuf payload
        r = handle_packet(b'RIP1' + pkt, mode=mode, save_path=save_path)
        if mode == Modes.ADD_BAG and r is not None:

            if previous_time is not None:
                current_sonar_frame_time += r.header.stamp.to_sec() - previous_time
            while True:
                topic, msg, t = next(input_bag_iterator)
                if t.to_sec() < current_sonar_frame_time:
                    output_bag.write(topic, msg, t)
                else:
                    print(f"t {t.to_sec()}-----writing SONAR MSG {current_sonar_frame_time}")
                    sonar_raw_msg = UInt8MultiArray()
                    sonar_raw_msg.data = list(b'RIP1' + pkt) # Convert bytes to a list of integers
                    output_bag.write(SONAR_POINT_CLOUD_TOPIC, sonar_raw_msg, rospy.Time.from_sec(current_sonar_frame_time))
                    break
            previous_time = r.header.stamp.to_sec()
        else:
            non_valid_packets += 1
    
    print(f"Non valid packets {non_valid_packets}/{len(packets)}")
    if mode == Modes.ADD_BAG:
        output_bag.close()



def check_file_existence(filename):
    try:
        with open(filename, 'rb') as f:
            pass
    except FileNotFoundError:
        print(f"File not found: {args.file}")
        exit(1)

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(
        description="Decode Sonar 3D-15 data from file or from multicast.")
    parser.add_argument(
        "--save",
        action="store_true",
        help="Save RangeImage data to XYZ file format and BitmapImage to PGM file format."
    )
    parser.add_argument(
        "--file",
        type=str,
        default="",
        help=f"Filename to parse -- neded for {Modes.FILE}."
    )
    parser.add_argument(
        "--mode",
        type=int,
        default="",
        help=f"mode {[(mode_member.value, mode_member.name) for mode_member in Modes]}."
    )
    parser.add_argument(
        "--rosbag_file",
        type=str,
        default="",
        help=f"Filename to parse -- neded for {Modes.ADD_BAG}."
    )
    # Parse arguments
    args = parser.parse_args()
    if args.mode == Modes.FILE.value:
        if args.mode == "file":
            if args.file:
                # Parse a file instead of listening to multicast
                print(f"Parsing file: {args.file}")
                check_file_existence(args.file)
                
                # parse_file(args.file, save=args.save) # TODO: place it back
                exit(0)
            else:
                print("No file specified. Use --file to specify a file to parse.")
                exit(1)

    elif args.mode == Modes.ROS.value:
        rospy.init_node(SONAR3D_FRAME)
        rospy.Subscriber(SONAR_RAW_DATA_TOPIC, UInt8MultiArray, sonar_msg_callback, queue_size=10)
        use_sensor_stamp = rospy.get_param('~use_sensor_stamp', USE_SENSOR_STAMP)
        pub_range_image = rospy.Publisher(SONAR_RANGE_IMAGE_TOPIC, Image, queue_size=10)
        pub_point_cloud = rospy.Publisher(SONAR_POINT_CLOUD_TOPIC, PointCloud, queue_size=10)

        bridge = CvBridge()
        print("ROS MODE")

        rospy.spin()

    elif args.mode == Modes.ADD_BAG.value:
        if args.file and args.rosbag_file:
            use_sensor_stamp = True
            # Parse a file instead of listening to multicast
            print(f"Parsing file: {args.file}")
            check_file_existence(args.file)
            check_file_existence(args.rosbag_file)
            
            bridge = CvBridge()
            parse_file(args.file, mode=Modes.ADD_BAG, rosbag_file=args.rosbag_file)
            exit(0)
        else:
            print("No file specified. Use --file to specify a file to parse.")
            exit(1)

